# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Prickle Press"
license = "MIT"
licenselink = "https://github.com/burrbd/pp-hugo-theme/blob/master/LICENSE.md"
description = "Theme used for pricklepress.co.uk"
homepage = "http://pricklepress.co.uk/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Bay Dodd"
